version: '3'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./code:/code/
    working_dir: /code
    ports:
      - "8000:8000"
    command: "python manage.py runserver 0:8000"
volumes:
  postgres-data:
